name: vaktijaba_fl
description: Vaktija za BiH

publish_to: 'none'

version: 2.1.1+2010102

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_qiblah: ^3.0.3
  scrollable_positioned_list: ^0.3.8
  hijri: ^3.0.0
  flutter_local_notifications: ^17.2.1+2
  provider: ^6.1.2
  flutter_slidable: ^3.1.1
  mailto: ^2.0.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.1
  quiver: ^3.2.1
  package_info_plus: ^8.0.1
  gap: ^3.0.1
  alarm: ^3.1.5
  permission_handler: ^11.3.1
  sound_mode: ^3.0.0
  workmanager: ^0.5.2
  disable_battery_optimization: ^1.1.1
  android_intent_plus: ^5.1.0
  flutter_timezone: ^2.1.0
  device_info_plus: ^10.1.1
  just_audio: ^0.9.39
  auto_start_flutter: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vaktija/
    - assets/icons/
    - assets/ezan/
    - lib/services/